feat(src/handler/controller/helper/updateItems): Validation of recieved data for updating an item. Response structured.
CebrasDevs/DescuentosYa pull request #67
Opened 2023-08-05 20:14 UTC by AlbertoMallar

--> El código puede ser un poco engorroso y quizás poco performante por tener esos if encadenados. Quizás puede mejorarse.
--> Se realizaron las pruebas básicas de funcionamiento tanto para manejo de errores por problemas con el ID o por datos insuficientes, como para el código funcionamiento de la actualización de las propiedades del item.
--> Revisar si el id que le enviamos al front está correcto siendo numérico. 

--> Finalmente, me faltó poner comentarios en alguna parte para acrlarar ciertas cosas, especialmente con el manejo del id.  Ésto puedo modificarlo en otro PR.
Para darles una idea más clara el id que usamos es el que se recibe por params. El id del objeto es provisoriamente borrado en el controler y luego se guarda en el helper igualándolo al  recibido por params anteriormente.

2023-08-05 20:39 UTC, SnowDevLC commented on server/src/helpers/itemsHelpers/updateItemsHelper.js
> +        data:  updateData
Hola Beto. Podrias podras el siguiente codigo que te dejo para simplificar desde la linea 12 a la 23. Probalo porque no lo probe, es una idea.

const updateData = {
        ...dataItem,
        id: dataItem.id === null ? +id : dataItem.id,
    };

    const res = await prisma.item.update({
        where: { id: +id },
        data: updateData,
    });

2023-08-05 23:19 UTC, wtfranco22 commented on server/src/helpers/itemsHelpers/updateItemsHelper.js
> +        data:  updateData
@SnowDevLC no quiero pasar por alto esa idea, pero este PR aplica getItems y lo van a necesitar en el front, entonces, la idea la vamos a aplicar y acepto el PR para que sigan continuando y eso va a ser una mejora para la proxima demo, donde si se utilizaran las rutas update

2023-08-05 23:20 UTC, wtfranco22 submitted a review, later dismissed

2023-08-06 02:34 UTC, misaelc98 requested changes
Necesito un ID para traer los details porfi (/getItemsByIdController)

2023-08-06 13:04 UTC, AlbertoMallar commented
> Necesito un ID para traer los details porfi (/getItemsByIdController)

Este pull request es para las rutas de update Items no para las de get items

2023-08-06 16:29 UTC, SnowDevLC approved these changes, later dismissed

2023-08-07 02:55 UTC, SnowDevLC approved these changes

2023-08-07 03:18 UTC, merged