feat(admin dashboard):dashboard created with its route
CebrasDevs/DescuentosYa pull request #78
Opened 2023-08-07 23:32 UTC by DelHoyoLorenzo

Primer intento de componente dashboard creado, en home hay un link en la navbar para dirigirse. Solo sucede si el activeUser tiene el rol de admin, y si se quiere acceder a la ruta siendo otro rol tampoco se puede.

Detalles a corregir:
-tanto un miembro como una compañia tienen que tener su nombre en el atributo name (nico ya sabe igual)
-habria que modificar como llega del back el phone number y el last payment:
![image](https://github.com/CebrasDevs/DescuentosYa/assets/129763514/17c4a457-5d5d-464a-b9f5-139da301f9ee)

2023-08-07 23:52 UTC, NicoGarcia12 commented
Creo que las pruebas, en este caso para un ADMIN, deberían hacerlas y si funciona eliminar esto para que no queden esas líneas. Y respecto al cambio por name, si querés te digo cómo y lo cambiás asi ya queda funcionando y no esperamos a un cambio futuro. Para los que son dateTime hay que formatearlo, pero es complejo porque tenemos que ver si está la posibilidad o no para el lunes de que pague cuota a través de la plataforma de alguna manera. Lo mismo con el teléfono, hay que hacerle algún formateo aunque sea básico y chau

2023-08-08 01:02 UTC, wtfranco22 requested changes

2023-08-08 01:02 UTC, wtfranco22 commented on client/src/components/Userdetail.jsx
> +        <h1>Phone number: {user.phone}</h1>
Nosotros ya tenemos la estructura de como enviar los datos del usuario, y el telefono se envia como phoneNumber, que es de la misma forma que nos envian desde el formulario @DelHoyoLorenzo

2023-08-08 03:01 UTC, wtfranco22 approved these changes

2023-08-08 12:06 UTC, SnowDevLC approved these changes

2023-08-08 12:08 UTC, merged